"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { useSearchParams } from "next/navigation";
import { Search } from "lucide-react";
import { DEFAULT_ZIP, getZipData, riskColor, searchZips } from "@/lib/mock-data";
import { useForecastWeek } from "@/lib/forecast-context";
import { RiskBadge } from "@/components/RiskBadge";
import { DetectionsBarChart } from "@/components/charts/DetectionsBarChart";
import type { ZipForecast } from "@/lib/types";

function ZipResults({ data }: { data: ZipForecast }) {
  const lastSix = data.weeklyHistory.filter((w) => w.week >= 27 && w.week <= 32);
  const chartData = lastSix.length ? lastSix : data.weeklyHistory.slice(-6);
  const factors = [
    { label: "Recent Positive Detections", ...data.indicators.recentPositiveDetections },
    { label: "Temperature (Last 7 Days)", ...data.indicators.temperature },
    { label: "Rainfall (Last 7 Days)", ...data.indicators.rainfall },
    { label: "Seasonality", ...data.indicators.seasonality },
  ];

  return (
    <div className="grid gap-4 xl:grid-cols-2">
      <section className="rounded-2xl border border-white/10 bg-[#131a2b] p-6">
        <div className="text-xs uppercase tracking-wider text-slate-500">ZIP</div>
        <h2 className="mt-1 text-3xl font-semibold text-white">{data.zip}</h2>
        <p className="mt-1 text-slate-300">{data.neighborhood}</p>
        <p className="text-sm text-slate-500">{data.borough}</p>
        <div className="mt-6 flex items-end justify-between gap-4">
          <div>
            <div className="text-xs text-slate-500">Forecast risk</div>
            <div className="text-5xl font-semibold" style={{ color: riskColor(data.riskLevel) }}>
              {data.riskScore}%
            </div>
          </div>
          <RiskBadge level={data.riskLevel} size="lg" />
        </div>
        <p className="mt-4 text-sm text-slate-400">{data.forecastRange}</p>
      </section>

      <section className="rounded-2xl border border-white/10 bg-[#131a2b] p-6">
        <h3 className="text-sm font-semibold text-white">Risk Factors</h3>
        <ul className="mt-4 space-y-3">
          {factors.map((f) => (
            <li
              key={f.label}
              className="flex items-center justify-between gap-3 rounded-xl border border-white/5 bg-[#0a0e1a] px-3 py-3"
            >
              <div>
                <div className="text-sm text-slate-200">{f.label}</div>
                <div className="text-xs text-slate-500">{f.value}</div>
              </div>
              <RiskBadge level={f.severity} />
            </li>
          ))}
        </ul>
      </section>

      <section className="rounded-2xl border border-white/10 bg-[#131a2b] p-6">
        <h3 className="text-sm font-semibold text-white">Recent Positive Detections</h3>
        <div className="mt-4 h-52">
          <DetectionsBarChart data={chartData} />
        </div>
      </section>

      <section className="rounded-2xl border border-[#22c55e]/25 bg-[#22c55e]/8 p-6">
        <div className="text-xs font-semibold uppercase tracking-wider text-[#4ade80]">
          Generated by Gemini
        </div>
        <p className="mt-3 text-sm leading-relaxed text-slate-200">{data.aiInsight}</p>
        <p className="mt-3 text-[11px] text-slate-500">
          Mock explanation for demo — not calling the Gemini API yet.
        </p>
      </section>
    </div>
  );
}

export function ZipLookupClient() {
  const searchParams = useSearchParams();
  const { week } = useForecastWeek();
  const initial = searchParams.get("zip") ?? DEFAULT_ZIP;
  const [query, setQuery] = useState(initial);
  const [activeZip, setActiveZip] = useState(initial);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    const z = searchParams.get("zip");
    if (z) {
      setQuery(z);
      setActiveZip(z);
    }
  }, [searchParams]);

  const data = useMemo(() => getZipData(activeZip, week), [activeZip, week]);
  const suggestions = searchZips(query, week);

  function onSubmit(e: FormEvent) {
    e.preventDefault();
    const found = getZipData(query, week) ?? suggestions[0];
    if (!found) {
      setError("No matching NYC ZIP in the mock dataset.");
      return;
    }
    setError(null);
    setActiveZip(found.zip);
    setQuery(found.zip);
  }

  return (
    <div className="mx-auto max-w-6xl space-y-5">
      <form onSubmit={onSubmit} className="flex gap-2">
        <div className="relative flex-1">
          <Search className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-500" />
          <input
            value={query}
            onChange={(e) => setQuery(e.target.value)}
            placeholder="Search ZIP, neighborhood, or borough — e.g. 10310"
            className="h-11 w-full rounded-xl border border-white/10 bg-[#131a2b] pl-10 pr-3 text-sm text-white outline-none ring-[#22c55e] placeholder:text-slate-500 focus:ring-2"
          />
        </div>
        <button
          type="submit"
          className="h-11 rounded-xl bg-[#22c55e] px-5 text-sm font-semibold text-[#052e16] hover:bg-[#4ade80]"
        >
          Search
        </button>
      </form>
      {query && suggestions.length > 0 && query !== activeZip && (
        <div className="flex flex-wrap gap-2">
          {suggestions.map((s) => (
            <button
              key={s.zip}
              type="button"
              onClick={() => {
                setActiveZip(s.zip);
                setQuery(s.zip);
                setError(null);
              }}
              className="rounded-full border border-white/10 bg-[#131a2b] px-3 py-1 text-xs text-slate-300 hover:border-[#22c55e]/40 hover:text-white"
            >
              {s.zip} · {s.neighborhood}
            </button>
          ))}
        </div>
      )}
      {error && <p className="text-sm text-red-400">{error}</p>}
      {data ? (
        <ZipResults data={data} />
      ) : (
        <p className="text-sm text-slate-400">Enter a ZIP to see the mock forecast.</p>
      )}
    </div>
  );
}
